name: Update the Digital Garden Repository

on:
  push:
    branches:
      - main

concurrency:
  group: "updates"
  cancel-in-progress: false

jobs:
  call-garden-workflow:
  run: |
    curl -L \
    -X POST \
    -H "Accept: application/vnd.github+json" \
    -H "Authorization: Bearer ${{ secrets.GARDEN_ACCESS_TOKEN }}" \
    https://api.github.com/repos/yavidor/digital-garden/actions/workflows/update-contents.yaml/dispatches

