name: Update the Digital Garden

on:
  push:
    branches:
      - main

concurrency:
  group: "updates"
  cancel-in-progress: false

jobs:
  call-garden-workflow:
    uses: yavidor/digital-garden/.github/workflows/.github/workflows/update-contents.yaml@v4

